/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemsdevelopment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ashleigh.halliday
 */
public class admin_customers_create extends javax.swing.JFrame {
    
    DefaultComboBoxModel genderTypeModel = new DefaultComboBoxModel();

    /**
     * Creates new form admin_customers_create
     */
    public admin_customers_create() {
        initComponents();
        refreshData();
    }
    
    public void refreshData() {
        try {
            String sqlGetTypes = "SELECT * FROM tbl_customer"; //select all data from db 
            
            Connection conn = db.Connect();
            
            JOptionPane.showMessageDialog(null, "ps");
            PreparedStatement ps = conn.prepareStatement(sqlGetTypes);
            
            JOptionPane.showMessageDialog(null, "rs");
            ResultSet rs = ps.executeQuery();
            
            JOptionPane.showMessageDialog(null, "remove all items");
            this.comboBoxGender.removeAllItems();
            
            JOptionPane.showMessageDialog(null, "while loop");
            while (rs.next()){
                genderTypeModel.addElement(new ComboBoxItem(rs.getInt("customerId"), rs.getString("gender")));
                JOptionPane.showMessageDialog(null, "added element?");
            }
            JOptionPane.showMessageDialog(null, "set model");
            this.comboBoxGender.setModel(genderTypeModel);
            
            rs = ps.executeQuery();
            
            //this.comboBoxUserRole.removeAllItems();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Cannot retrieve users! Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateNewCustomer = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCustomerDetails = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAddressLine1 = new javax.swing.JLabel();
        lblTown = new javax.swing.JLabel();
        lblCounty = new javax.swing.JLabel();
        lblPostcode = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        txtEnterFirstName = new javax.swing.JTextField();
        txtEnterSurname = new javax.swing.JTextField();
        txtEnterDOB = new javax.swing.JTextField();
        txtEnterAddressLine1 = new javax.swing.JTextField();
        txtEnterTown = new javax.swing.JTextField();
        txtEnterCounty = new javax.swing.JTextField();
        txtEnterPostcode = new javax.swing.JTextField();
        txtEnterPhoneNumber = new javax.swing.JTextField();
        txtEnterEmailAddress = new javax.swing.JTextField();
        comboBoxGender = new javax.swing.JComboBox<>();
        lblPaymentInformation = new javax.swing.JLabel();
        lblNameOnCard = new javax.swing.JLabel();
        lblCVVNumber = new javax.swing.JLabel();
        lblCardNumber = new javax.swing.JLabel();
        lblExpiryDate = new javax.swing.JLabel();
        txtEnterNameOnCard = new javax.swing.JTextField();
        txtEnterCardNumber = new javax.swing.JTextField();
        txtEnterCVVNumber = new javax.swing.JTextField();
        txtEnterExpiryDate = new javax.swing.JTextField();
        btnCreateCustomer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCreateNewCustomer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCreateNewCustomer.setText("Create a New Customer");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCustomerDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCustomerDetails.setText("Customer Details:");

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFirstName.setText("First Name:");

        lblSurname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSurname.setText("Surname:");

        lblDOB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDOB.setText("DOB:");

        lblGender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGender.setText("Gender:");

        lblAddressLine1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAddressLine1.setText("Address Line 1:");

        lblTown.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTown.setText("Town:");

        lblCounty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCounty.setText("County:");

        lblPostcode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPostcode.setText("Postcode:");

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhoneNumber.setText("Phone Number:");

        lblEmailAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmailAddress.setText("Email Address:");

        comboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        lblPaymentInformation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPaymentInformation.setText("Payment Information:");

        lblNameOnCard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNameOnCard.setText("Name on Card:");

        lblCVVNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCVVNumber.setText("CVV Number:");

        lblCardNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCardNumber.setText("Card Number:");

        lblExpiryDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExpiryDate.setText("Expiry Date:");

        btnCreateCustomer.setText("Create Customer");
        btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerDetails)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblSurname)
                            .addComponent(lblDOB)
                            .addComponent(lblGender)
                            .addComponent(lblAddressLine1)
                            .addComponent(lblTown)
                            .addComponent(lblCounty)
                            .addComponent(lblPostcode)
                            .addComponent(lblPhoneNumber)
                            .addComponent(lblEmailAddress))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEnterFirstName)
                            .addComponent(txtEnterSurname)
                            .addComponent(txtEnterDOB)
                            .addComponent(txtEnterAddressLine1)
                            .addComponent(txtEnterTown)
                            .addComponent(txtEnterCounty)
                            .addComponent(txtEnterPostcode)
                            .addComponent(txtEnterPhoneNumber)
                            .addComponent(txtEnterEmailAddress)
                            .addComponent(comboBoxGender, 0, 160, Short.MAX_VALUE))))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNameOnCard)
                        .addGap(57, 57, 57)
                        .addComponent(txtEnterNameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCVVNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPaymentInformation)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCardNumber)
                                        .addComponent(lblExpiryDate))
                                    .addGap(63, 63, 63)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEnterExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEnterCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEnterCVVNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCreateNewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(btnCreateCustomer)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(lblCreateNewCustomer)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaymentInformation, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCustomerDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtEnterFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameOnCard)
                    .addComponent(txtEnterNameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname)
                    .addComponent(txtEnterSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCardNumber)
                    .addComponent(txtEnterCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtEnterDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExpiryDate)
                    .addComponent(txtEnterExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(comboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCVVNumber)
                    .addComponent(txtEnterCVVNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddressLine1)
                    .addComponent(txtEnterAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTown)
                    .addComponent(txtEnterTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCounty)
                    .addComponent(txtEnterCounty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostcode)
                    .addComponent(txtEnterPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNumber)
                    .addComponent(txtEnterPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailAddress)
                    .addComponent(txtEnterEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnCreateCustomer)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //user to retun to manage customers page
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new admin_system_users().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    //creates a new user
    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed
        try{
            JOptionPane.showMessageDialog(null, "cbi");
            ComboBoxItem gender = (ComboBoxItem)genderTypeModel.getSelectedItem(); //get the users role from combo box
            
            JOptionPane.showMessageDialog(null, "conn");
            Connection conn = db.Connect();
            
            JOptionPane.showMessageDialog(null, "sql insert");
            String sqlInsertUser = "INSERT INTO tbl_customer (firstName, surname, dob, gender, addressLine1, town, county, postcode, phoneNumber, emailAddress, nameOnCard, cardNumber, expiryDate, cvvNumber)"
                                 + "VALUES                   (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            JOptionPane.showMessageDialog(null, "ps");
            PreparedStatement ps = conn.prepareStatement(sqlInsertUser);
            ps.setString(1, this.txtEnterFirstName.getText());
            ps.setString(2, this.txtEnterSurname.getText());
            ps.setString(3, this.txtEnterDOB.getText());
            ps.setString(4, String.valueOf(gender));
            ps.setString(5, this.txtEnterAddressLine1.getText());
            ps.setString(6, this.txtEnterTown.getText());
            ps.setString(7, this.txtEnterCounty.getText());
            ps.setString(8, this.txtEnterPostcode.getText());
            ps.setString(9, this.txtEnterPhoneNumber.getText());
            ps.setString(10, this.txtEnterEmailAddress.getText());
            ps.setString(11, this.txtEnterNameOnCard.getText());
            ps.setString(12, this.txtEnterCardNumber.getText());
            ps.setString(13, this.txtEnterExpiryDate.getText());
            ps.setString(14, this.txtEnterCVVNumber.getText());
            
            JOptionPane.showMessageDialog(null, sqlInsertUser);
            
            JOptionPane.showMessageDialog(null, "execute me pls");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Customer has been successfully created");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Customer could not be created. Please try again. Error: " + e);
        }
        
        admin_customers ac = new admin_customers();
        ac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_customers_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_customers_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_customers_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_customers_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_customers_create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JComboBox<String> comboBoxGender;
    private javax.swing.JLabel lblAddressLine1;
    private javax.swing.JLabel lblCVVNumber;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblCounty;
    private javax.swing.JLabel lblCreateNewCustomer;
    private javax.swing.JLabel lblCustomerDetails;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblExpiryDate;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblNameOnCard;
    private javax.swing.JLabel lblPaymentInformation;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPostcode;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTown;
    private javax.swing.JTextField txtEnterAddressLine1;
    private javax.swing.JTextField txtEnterCVVNumber;
    private javax.swing.JTextField txtEnterCardNumber;
    private javax.swing.JTextField txtEnterCounty;
    private javax.swing.JTextField txtEnterDOB;
    private javax.swing.JTextField txtEnterEmailAddress;
    private javax.swing.JTextField txtEnterExpiryDate;
    protected javax.swing.JTextField txtEnterFirstName;
    private javax.swing.JTextField txtEnterNameOnCard;
    private javax.swing.JTextField txtEnterPhoneNumber;
    private javax.swing.JTextField txtEnterPostcode;
    private javax.swing.JTextField txtEnterSurname;
    private javax.swing.JTextField txtEnterTown;
    // End of variables declaration//GEN-END:variables
}
