/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemsdevelopment;

import javax.swing.JOptionPane;

/**
 *
 * @author ashleigh.halliday
 */
public class adminDashboard extends javax.swing.JFrame {

    /**
     */
    public adminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        adminMenuBar = new javax.swing.JMenuBar();
        btnManageSystemUsers = new javax.swing.JMenu();
        btnManageCustomers = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        adminLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(895, 517));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("The Tech Peeps");
        lblTitle.setToolTipText("");

        adminMenuBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 2, true));
        adminMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminMenuBar.setMinimumSize(new java.awt.Dimension(563, 40));
        adminMenuBar.setPreferredSize(new java.awt.Dimension(563, 40));

        btnManageSystemUsers.setText("System Users");
        btnManageSystemUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageSystemUsersMouseClicked(evt);
            }
        });
        adminMenuBar.add(btnManageSystemUsers);

        btnManageCustomers.setText("Customers");
        btnManageCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageCustomersMouseClicked(evt);
            }
        });
        adminMenuBar.add(btnManageCustomers);

        jMenu3.setText("Customer Contacts");
        adminMenuBar.add(jMenu3);

        jMenu4.setText("Customer Cases");
        adminMenuBar.add(jMenu4);

        jMenu5.setText("Subscriptions");
        adminMenuBar.add(jMenu5);

        jMenu6.setText("Audit Trail");
        adminMenuBar.add(jMenu6);

        adminLogout.setText("Logout");
        adminLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLogoutMouseClicked(evt);
            }
        });
        adminMenuBar.add(adminLogout);
        adminLogout.getAccessibleContext().setAccessibleDescription("");

        setJMenuBar(adminMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(330, 330, 330))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblTitle)
                .addContainerGap(404, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //log admin user out
    private void adminLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLogoutMouseClicked
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_adminLogoutMouseClicked

    //open manage system users
    private void btnManageSystemUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageSystemUsersMouseClicked
        setVisible(false);
        new admin_system_users().setVisible(true);
    }//GEN-LAST:event_btnManageSystemUsersMouseClicked

    //open manage customers
    private void btnManageCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageCustomersMouseClicked
        setVisible(false);
        new admin_customers().setVisible(true);
    }//GEN-LAST:event_btnManageCustomersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboard().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminLogout;
    private javax.swing.JMenuBar adminMenuBar;
    private javax.swing.JMenu btnManageCustomers;
    private javax.swing.JMenu btnManageSystemUsers;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
