/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemsdevelopment;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ashleigh.halliday
 */
public class admin_system_users_create extends javax.swing.JFrame {

    DefaultComboBoxModel roleTypeModel = new DefaultComboBoxModel();
    /**
     * Creates new form admin_system_users_create
     */
    public admin_system_users_create() {
        initComponents();
        refreshData();
    }
    
    public void refreshData() {
        try {
            String sqlGetTypes = "SELECT * FROM tbl_login"; //select all data from db 
            
            Connection conn = db.Connect();
            
            JOptionPane.showMessageDialog(null, "ps");
            PreparedStatement ps = conn.prepareStatement(sqlGetTypes);
            
            JOptionPane.showMessageDialog(null, "rs");
            ResultSet rs = ps.executeQuery();
            
            JOptionPane.showMessageDialog(null, "remove all items");
            this.comboBoxUserRole.removeAllItems();
            
            JOptionPane.showMessageDialog(null, "while loop");
            while (rs.next()){
                roleTypeModel.addElement(new ComboBoxItem(rs.getInt("id"), rs.getString("username")));
                JOptionPane.showMessageDialog(null, "added element?");
            }
            JOptionPane.showMessageDialog(null, "set model");
            this.comboBoxUserRole.setModel(roleTypeModel);
            
            rs = ps.executeQuery();
            
            //this.comboBoxUserRole.removeAllItems();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Cannot retrieve users! Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateNewUser = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        txtEnterPassword = new javax.swing.JTextField();
        txtEnterUsername = new javax.swing.JTextField();
        comboBoxUserRole = new javax.swing.JComboBox<>();
        btnCreateUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(537, 592));

        lblCreateNewUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCreateNewUser.setText("Create New User");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword.setText("Password:");

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole.setText("Role:");

        comboBoxUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Team Leader", "Agent" }));

        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblRole)
                            .addComponent(lblUsername))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEnterPassword)
                                .addComponent(comboBoxUserRole, 0, 232, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCreateNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCreateUser)
                        .addGap(218, 218, 218))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addGap(43, 43, 43)
                .addComponent(lblCreateNewUser)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtEnterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtEnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(comboBoxUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(btnCreateUser)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //user clicks to return to admin system users page
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new admin_system_users().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    //user clicks create user button
    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        try{
            JOptionPane.showMessageDialog(null, "cbi");
            ComboBoxItem role = (ComboBoxItem)roleTypeModel.getSelectedItem(); //get the users role from combo box
            
            JOptionPane.showMessageDialog(null, "conn");
            Connection conn = db.Connect();
            
            JOptionPane.showMessageDialog(null, "sql insert");
            String sqlInsertUser = "INSERT INTO tbl_login (username, password, role)"
                                 + "VALUES                (?, ?, ?)";
            JOptionPane.showMessageDialog(null, "ps");
            PreparedStatement ps = conn.prepareStatement(sqlInsertUser);
            ps.setString(1, this.txtEnterUsername.getText());
            ps.setString(2, this.txtEnterPassword.getText());
            ps.setString(3, String.valueOf(role));
            
            JOptionPane.showMessageDialog(null, sqlInsertUser);
            
            JOptionPane.showMessageDialog(null, "execute me pls");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "User has been successfully created");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "User could not be created. Please try again. Error: " + e);
        }
        
        admin_system_users asu = new admin_system_users();
        asu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_system_users_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_system_users_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_system_users_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_system_users_create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_system_users_create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox<String> comboBoxUserRole;
    private javax.swing.JLabel lblCreateNewUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtEnterPassword;
    private javax.swing.JTextField txtEnterUsername;
    // End of variables declaration//GEN-END:variables
}
